"""
mertens_manim.py  —  Manim animation of M(x) with zeta-zero approximation

The explicit formula:
    M(x) ≈ Σ_{ρ}  x^ρ / (ρ ζ'(ρ))   (sum over non-trivial zeta zeros)
         = 2 Re[ Σ_{γ>0}  x^(1/2+iγ) / ((1/2+iγ) ζ'(1/2+iγ)) ]   − 2
  (each conjugate pair contributes 2× real part; constant −2 comes from the
   pole of 1/ζ(s) at s=0)

Animation sequence:
  1. Title card
  2. Draw true M(x) step-function (grey), 1 → 10^10, log x-axis
  3. Formula appears; approximation curve grows as we add 1 → 5 → 20 → 50 zeros
  4. Final frame shows both curves together with legend
"""

from manim import *
import numpy as np
import mpmath as mp
from scipy.special import j0
from scipy.interpolate import interp1d


# ── pre-computed zeta zeros (γ_n) and coefficients 1/(ρ_n ζ'(ρ_n)) ──────────
# Generated by mpmath; each entry: {rho_re, rho_im, coeff_re, coeff_im}
# ZEROS_DATA = [
#     {"rho_re": 0.5, "rho_im": 14.134725141734694, "coeff_re": -0.010893854269763689, "coeff_im": -0.08847335629435403},
#     {"rho_re": 0.5, "rho_im": 21.022039638771555, "coeff_re": 0.010119688068273213, "coeff_im": -0.04058944497965842},
#     {"rho_re": 0.5, "rho_im": 25.01085758014569, "coeff_re": -0.009008618636777258, "coeff_im": -0.027715014748218635},
#     {"rho_re": 0.5, "rho_im": 30.424876125859513, "coeff_re": 0.013255659620100047, "coeff_im": -0.021435085780716966},
#     {"rho_re": 0.5, "rho_im": 32.93506158773919, "coeff_re": -0.011646943891948376, "coeff_im": -0.018623694028736984},
#     {"rho_re": 0.5, "rho_im": 37.58617815882567, "coeff_re": 0.004153753994718049, "coeff_im": -0.013093978481484344},
#     {"rho_re": 0.5, "rho_im": 40.918719012147496, "coeff_re": 0.003527354741619671, "coeff_im": -0.016009802316682726},
#     {"rho_re": 0.5, "rho_im": 43.32707328091499, "coeff_re": -0.007461063047817406, "coeff_im": -0.010137823673614988},
#     {"rho_re": 0.5, "rho_im": 48.005150881167156, "coeff_re": 0.010077673028534408, "coeff_im": -0.008654917882866117},
#     {"rho_re": 0.5, "rho_im": 49.773832477672294, "coeff_re": -0.006366938046267059, "coeff_im": -0.012646337484892226},
#     {"rho_re": 0.5, "rho_im": 52.97032147771992, "coeff_re": -0.0019302074200892083, "coeff_im": -0.007535742009440994},
#     {"rho_re": 0.5, "rho_im": 56.44624769706339, "coeff_re": 0.0026915455025041437, "coeff_im": -0.006979912337875024},
#     {"rho_re": 0.5, "rho_im": 59.34704400260249, "coeff_re": 0.005231695682261124, "coeff_im": -0.010917060218490254},
#     {"rho_re": 0.5, "rho_im": 60.831778524609375, "coeff_re": -0.008460905459994584, "coeff_im": -0.005211730018093082},
#     {"rho_re": 0.5, "rho_im": 65.11254405236059, "coeff_re": 0.004681521688773571, "coeff_im": -0.004809835879413827},
#     {"rho_re": 0.5, "rho_im": 67.07980992471482, "coeff_re": -0.00046063068282793124, "coeff_im": -0.008344741474820228},
#     {"rho_re": 0.5, "rho_im": 69.54640171971203, "coeff_re": -0.0016543124065745296, "coeff_im": -0.006365264697052046},
#     {"rho_re": 0.5, "rho_im": 72.06715767475817, "coeff_re": -0.0015758068028736285, "coeff_im": -0.004406530200374267},
#     {"rho_re": 0.5, "rho_im": 75.70469069144065, "coeff_re": 0.006234164019208978, "coeff_im": -0.004029350497668567},
#     {"rho_re": 0.5, "rho_im": 77.14484006887073, "coeff_re": -0.003012934316028597, "coeff_im": -0.008367370375484534},
#     {"rho_re": 0.5, "rho_im": 79.33737502796754, "coeff_re": -0.0031602011782673014, "coeff_im": -0.0035843682143186716},
#     {"rho_re": 0.5, "rho_im": 82.91038085885298, "coeff_re": 0.002975943888869688, "coeff_im": -0.0034962879474948375},
#     {"rho_re": 0.5, "rho_im": 84.73549290327877, "coeff_re": -0.0003938310726534818, "coeff_im": -0.005444969826196116},
#     {"rho_re": 0.5, "rho_im": 87.42527493020835, "coeff_re": 0.0019138476018558427, "coeff_im": -0.006058255703427694},
#     {"rho_re": 0.5, "rho_im": 88.80911120564731, "coeff_re": -0.004376872064804695, "coeff_im": -0.002759357893527696},
#     {"rho_re": 0.5, "rho_im": 92.49189982837479, "coeff_re": 0.002490788462126979, "coeff_im": -0.0025958393543428244},
#     {"rho_re": 0.5, "rho_im": 94.65134404779338, "coeff_re": 0.003665724855440117, "coeff_im": -0.006128847673694208},
#     {"rho_re": 0.5, "rho_im": 95.87063425978465, "coeff_re": -0.004992370568929498, "coeff_im": -0.0036073261421478523},
#     {"rho_re": 0.5, "rho_im": 98.83119421985536, "coeff_re": -8.709034059820017e-05, "coeff_im": -0.0028769396847764574},
#     {"rho_re": 0.5, "rho_im": 101.31785100573138, "coeff_re": 0.0008329404397459617, "coeff_im": -0.003016424208977455},
#     {"rho_re": 0.5, "rho_im": 103.72553804047329, "coeff_re": 0.002089785386887085, "coeff_im": -0.003926913866001836},
#     {"rho_re": 0.5, "rho_im": 105.44662305232062, "coeff_re": -0.0011671985048476042, "coeff_im": -0.004925376069116048},
#     {"rho_re": 0.5, "rho_im": 107.16861118427572, "coeff_re": -0.0025249960617490073, "coeff_im": -0.001848049826741851},
#     {"rho_re": 0.5, "rho_im": 111.02953554316966, "coeff_re": 0.005604861047521012, "coeff_im": -0.0007978742978867026},
#     {"rho_re": 0.5, "rho_im": 111.87465917699263, "coeff_re": -0.003131375124649218, "coeff_im": -0.005772024462887029},
#     {"rho_re": 0.5, "rho_im": 114.32022091545004, "coeff_re": -0.0003578408571614553, "coeff_im": -0.003416812851990427},
#     {"rho_re": 0.5, "rho_im": 116.22667963750765, "coeff_re": -0.0012559218523193866, "coeff_im": -0.0024562175979568847},
#     {"rho_re": 0.5, "rho_im": 118.79078286597744, "coeff_re": 0.00030245718165578354, "coeff_im": -0.0021438068882027504},
#     {"rho_re": 0.5, "rho_im": 121.37012500242093, "coeff_re": 0.0025835012521523455, "coeff_im": -0.0024928165553289226},
#     {"rho_re": 0.5, "rho_im": 122.94682936990842, "coeff_re": 4.649424193960408e-06, "coeff_im": -0.005216955437698},
#     {"rho_re": 0.5, "rho_im": 124.25681855434819, "coeff_re": -0.003224966543553688, "coeff_im": -0.001293943143887803},
#     {"rho_re": 0.5, "rho_im": 127.51668387959671, "coeff_re": 0.0010487839534895636, "coeff_im": -0.0016932476965040574},
#     {"rho_re": 0.5, "rho_im": 129.57870421672569, "coeff_re": 0.001651105694264879, "coeff_im": -0.0028489521208254053},
#     {"rho_re": 0.5, "rho_im": 131.0876885090455, "coeff_re": -0.0010619380680742558, "coeff_im": -0.003111710218225847},
#     {"rho_re": 0.5, "rho_im": 133.4977372312946, "coeff_re": 0.0006547791424827543, "coeff_im": -0.003206228219879565},
#     {"rho_re": 0.5, "rho_im": 134.75651050117528, "coeff_re": -0.0022362756131869095, "coeff_im": -0.0013928831750688476},
#     {"rho_re": 0.5, "rho_im": 138.11604205853885, "coeff_re": 0.0019459697009578396, "coeff_im": -0.0012090455289421963},
#     {"rho_re": 0.5, "rho_im": 139.73620895212138, "coeff_re": 0.0014779993024003018, "coeff_im": -0.003686789521040948},
#     {"rho_re": 0.5, "rho_im": 141.12370740402112, "coeff_re": -0.001996876898523065, "coeff_im": -0.0028879049476026007},
#     {"rho_re": 0.5, "rho_im": 143.11184580762204, "coeff_re": -0.001122052700827717, "coeff_im": -0.0014875752716316028},
# ]

# ── pre-computed M(x) data (true values from hyperbola DP) ──────────────────
# We'll compute this on-the-fly for the plot points using a simple sieve
def build_mertens_data(x_max=10**10, n_pts=800):
    """Build arrays of (x, M(x)) for plotting, using sieve for small x."""
    # For up to 10^8 use direct sieve; above that use floor-quotient values
    import math

    u = min(x_max, 10**8)

    # Sieve of mu up to u
    mu = [0] * (u + 1)
    mu[1] = 1
    primes = []
    is_composite = bytearray(u + 1)
    for i in range(2, u + 1):
        if not is_composite[i]:
            primes.append(i)
            mu[i] = -1
        for p in primes:
            if i * p > u:
                break
            is_composite[i * p] = 1
            if i % p == 0:
                mu[i * p] = 0
                break
            else:
                mu[i * p] = -mu[i]

    # Cumulative sum = M
    M_arr = [0] * (u + 1)
    for i in range(1, u + 1):
        M_arr[i] = M_arr[i - 1] + mu[i]

    # Sample log-spaced points up to u
    xs_small = np.unique(np.round(np.logspace(0, np.log10(u), n_pts * 4 // 5)).astype(int))
    xs_small = xs_small[xs_small >= 1]
    Ms_small = np.array([M_arr[int(x)] for x in xs_small], dtype=float)

    if x_max <= u:
        return xs_small.astype(float), Ms_small

    # For x > u: need hyperbola DP (simplified — use floor-quotients of x_max)
    # We'll pre-compute a handful of key points via the explicit formula (approximate)
    # and supplement with the main DP results imported from mertens_large.py
    # For the Manim animation, use only sieve range (up to 1e8) + known values
    # Known M values at powers of 10:
    known_large = {
        10**9: -222,
        2*10**9: 1037,    # approximate placeholder
        5*10**9: -5000,   # placeholder
        10**10: -33722,
    }
    # Just use sieve for the animation up to 1e8, which is visually rich
    return xs_small.astype(float), Ms_small


def M_approx_vectorised(xs, n_zeros=20):
    """Vectorised evaluation of the zeta-zero approximation formula."""
    logxs = np.log(xs)
    sqxs  = np.sqrt(xs)
    result = np.full(len(xs), -2.0)
    nf = -1.

    for n in range(1, 40):
        # nf *= -n / (4*PI*PI)
        k = 2 * n
        nf *= -k * (k-1) / (4*PI*PI)
        zeta0 = mp.zeta(2*n+1)
        zeta = float(zeta0.real)
        term = np.pow(xs, -k) / (n * zeta * nf)
        result += term
        # print(term[0])


    # for i, z in enumerate(ZEROS_DATA[:n_zeros]):
    for i in range(n_zeros):
        rho = mp.zetazero(i+1)
        gamma = float(rho.imag)
        zetad = mp.zeta(rho, derivative=1)
        coeff = 1. / (rho * zetad)
        # print(i, gamma, 'coeff:', coeff)
        # gamma = z['rho_im']
        # cr    = z['coeff_re']
        # ci    = z['coeff_im']
        # x^(1/2 + i*gamma) = sqrt(x) * exp(i*gamma*log(x))
        cr = float(coeff.real)
        ci = float(coeff.imag)
        cos_g = np.cos(gamma * logxs)
        sin_g = np.sin(gamma * logxs)
        # Re[ coeff * x^rho ] = sqx * (cr*cos - ci*sin)
        result += 2.0 * sqxs * (cr * cos_g - ci * sin_g)

    return result


# ── colour palette ─────────────────────────────────────────────────────────────
BG       = "#0a0a12"
TRUE_COL = "#4fc3f7"   # light blue — true M(x)
APP_COL  = "#ff6b6b"   # coral/red  — approximation
GRID_COL = "#1e2235"
AXIS_COL = "#3a4060"
TEXT_COL = "#e8eaf6"
GOLD     = "#ffd54f"
MINT     = "#69f0ae"


# ── helper: build a ParametricFunction tracing M(x) on log axis ──────────────
class MertensScene(Scene):
    def construct(self):
        self.camera.background_color = BG

        # ── build data ───────────────────────────────────────────────────────
        # Use log-spaced x from 2 to 10^8 (sieve is exact here)
        N_PLOT = 1200
        xs_plot = np.unique(np.round(np.logspace(
            np.log10(2), 8, N_PLOT)).astype(int)).astype(float)

        xs_plot2 = np.exp(np.linspace(np.log(xs_plot[0]), np.log(xs_plot[-1]), N_PLOT*4)).astype(float)

        print(xs_plot2)
        print(xs_plot2.shape)
        print(xs_plot2[:20])

        # Build sieve M values
        print("Building sieve...", flush=True)
        u = int(xs_plot.max())
        mu = np.ones(u + 1, dtype=np.int8); mu[0] = 0
        sq = int(u**0.5) + 1
        isp = np.ones(sq + 1, dtype=bool); isp[0] = isp[1] = False
        for p in range(2, int(sq**0.5) + 1):
            if isp[p]: isp[p*p::p] = False
        small_p = np.where(isp)[0].tolist()
        for p in small_p:
            mu[p::p] *= -1
            p2 = p * p
            if p2 <= u: mu[p2::p2] = 0
        cof = np.arange(u + 1, dtype=np.int32)
        for p in small_p: cof[p::p] //= p
        mu[(cof != 1) & (mu != 0)] *= -1
        M_sieve = np.cumsum(mu[1:]).astype(float)
        M_sieve = np.concatenate([[0.0], M_sieve])
        Ms_true = M_sieve[xs_plot.astype(int)]
        print("Sieve done.", flush=True)
        print(mu[:20])
        print(M_sieve[:20])
        print(Ms_true[:20])

        # approx at several zero counts
        Ms_1  = M_approx_vectorised(xs_plot2, 0)
        Ms_5  = M_approx_vectorised(xs_plot2, 1)
        Ms_20 = M_approx_vectorised(xs_plot2, 10)
        Ms_50 = M_approx_vectorised(xs_plot2, 400)

        print(Ms_50[:20])

        # ── axes setup ──────────────────────────────────────────────────────
        # x-axis: log scale, x in [2, 1e8]  →  t = log10(x) in [0.3, 8]
        # y-axis: M in [-3000, 2000] (rough range for 1..1e8)
        Y_MIN, Y_MAX = -3000, 2500
        X_LOG_MIN, X_LOG_MAX = np.log10(2), 8.0

        ax = Axes(
            x_range=[X_LOG_MIN, X_LOG_MAX, 1],
            # y_range=[Y_MIN, Y_MAX, 1000],
            y_range=[-1, 1, 1],
            x_length=11,
            y_length=5.5,
            axis_config={
                "color": AXIS_COL,
                "stroke_width": 1.5,
                "include_tip": False,
            },
            x_axis_config={"include_numbers": False},
            y_axis_config={"include_numbers": True,
                           "numbers_to_include": [-2000, -1000, 0, 1000, 2000],
                           "font_size": 18, "color": TEXT_COL},
        ).shift(DOWN * 0.4)

        # Manual x tick labels at powers of 10
        x_tick_vals = [1, 2, 3, 4, 5, 6, 7, 8]
        x_tick_labels = []
        for v in x_tick_vals:
            lbl = MathTex(f"10^{{{v}}}", font_size=16, color=TEXT_COL)
            pt  = ax.c2p(v, Y_MIN)
            lbl.next_to(pt, DOWN, buff=0.15)
            x_tick_labels.append(lbl)

        # tick marks
        x_ticks = VGroup(*[
            Line(ax.c2p(v, Y_MIN), ax.c2p(v, Y_MIN) + DOWN*0.08,
                 stroke_width=1, color=AXIS_COL)
            for v in x_tick_vals
        ])

        # grid lines
        grid = VGroup(*[
            Line(ax.c2p(v, Y_MIN), ax.c2p(v, Y_MAX),
                 stroke_width=0.4, color=GRID_COL)
            for v in x_tick_vals
        ], *[
            Line(ax.c2p(X_LOG_MIN, y), ax.c2p(X_LOG_MAX, y),
                 stroke_width=0.4, color=GRID_COL)
            for y in range(-3000, 3000, 500)
        ])

        zero_line = Line(ax.c2p(X_LOG_MIN, 0), ax.c2p(X_LOG_MAX, 0),
                         stroke_width=0.8, color=AXIS_COL)

        # Helper: build a VMobject polyline from xs, Ms arrays
        def make_curve(xs_plot, Ms_arr, color, sw=1.5, opacity=1.0):
            # map xs_plot (log) to manim coords
            pts = []
            for lx, m, scale in zip(np.log10(xs_plot), Ms_arr, np.sqrt(xs_plot)):
                p = ax.c2p(lx, m / max(scale, 1))
                pts.append(p)
            curve = VMobject(color=color, stroke_width=sw, stroke_opacity=opacity)
            curve.set_points_as_corners(pts)
            return curve

        # sqrt bounds
        sq_upper = make_curve(xs_plot, np.sqrt(xs_plot), WHITE, sw=0.7, opacity=0.25)
        sq_lower = make_curve(xs_plot, -np.sqrt(xs_plot), WHITE, sw=0.7, opacity=0.25)

        true_curve = make_curve(xs_plot, Ms_true, TRUE_COL, sw=1.2)
        app_1      = make_curve(xs_plot2, Ms_1,  APP_COL, sw=1.4)
        app_5      = make_curve(xs_plot2, Ms_5,  APP_COL, sw=1.4)
        app_20     = make_curve(xs_plot2, Ms_20, APP_COL, sw=1.6)
        app_50     = make_curve(xs_plot2, Ms_50, GOLD,    sw=1.8)

        # ── labels ──────────────────────────────────────────────────────────
        title = VGroup(
            MathTex(r"M(x) = \sum_{n \leq x} \mu(n)",
                    font_size=36, color=TEXT_COL),
            Text("and the Riemann zeta zeros", font_size=20, color=AXIS_COL)
        ).arrange(DOWN, buff=0.15).to_edge(UP, buff=0.25)

        x_label = MathTex("x", font_size=22, color=TEXT_COL).next_to(
            ax.c2p(X_LOG_MAX, Y_MIN), RIGHT, buff=0.1)
        y_label = MathTex("M(x)", font_size=20, color=TEXT_COL).rotate(PI/2).next_to(
            ax.c2p(X_LOG_MIN, 0), LEFT, buff=0.25)

        explicit_formula = MathTex(
            r"M(x) \approx \sum_{|\gamma| \leq T} \frac{x^\rho}{\rho\,\zeta'(\rho)}",
            font_size=28, color=APP_COL
        ).to_corner(UR, buff=0.45).shift(DOWN * 1.4)

        # Legend
        def legend_item(color, text_str, fs=18):
            dot  = Dot(color=color, radius=0.07)
            line = Line(ORIGIN, RIGHT * 0.4, color=color, stroke_width=2.5)
            lbl  = Text(text_str, font_size=fs, color=TEXT_COL)
            return VGroup(VGroup(line, dot.next_to(line, RIGHT, buff=0)).arrange(RIGHT, buff=0), lbl).arrange(RIGHT, buff=0.15)

        leg_true  = legend_item(TRUE_COL, "True M(x)")
        leg_app   = legend_item(APP_COL,  "Zeta approx.")
        leg_sqrt  = legend_item(WHITE,    "±√x bound")
        legend = VGroup(leg_true, leg_app, leg_sqrt).arrange(DOWN, buff=0.2, aligned_edge=LEFT)
        legend.to_corner(UL, buff=0.4).shift(DOWN * 1.2 + RIGHT * 0.1)

        zero_count_label = always_redraw(lambda: Text("", font_size=1))

        # ── n-zeros counter ──────────────────────────────────────────────────
        n_tracker = ValueTracker(0)

        def make_zero_lbl(n):
            return VGroup(
                Text("zeros used:", font_size=18, color=AXIS_COL),
                Text(str(n), font_size=28, color=GOLD, weight=BOLD),
            ).arrange(RIGHT, buff=0.2).to_corner(UR, buff=0.45).shift(DOWN * 2.4)

        # ── ANIMATION SEQUENCE ───────────────────────────────────────────────

        # 1. Title
        self.add(title)

        # 2. Axes appear
        self.play(
            Create(grid),
            Create(ax),
            Create(zero_line),
            Create(x_ticks),
            *[Write(lbl) for lbl in x_tick_labels],
            Write(x_label), Write(y_label),
            run_time=1.5
        )
        self.wait(0.3)

        # 3. sqrt bounds
        self.play(
            Create(sq_upper), Create(sq_lower),
            run_time=0.8
        )
        sq_label = MathTex(r"\pm\sqrt{x}", font_size=18, color=WHITE, fill_opacity=0.5
                           ).next_to(ax.c2p(7.5, np.sqrt(10**7.5)), UP, buff=0.08)
        self.play(FadeIn(sq_label), run_time=0.4)

        # 4. Draw true M(x)
        self.play(
            Create(true_curve, rate_func=linear),
            run_time=2.5
        )
        lbl_true = Text("True M(x)", font_size=18, color=TRUE_COL).next_to(
            ax.c2p(7.2, Ms_true[int(len(Ms_true)*0.85)]), UP, buff=0.15)
        self.play(FadeIn(lbl_true), run_time=0.5)

        # 5. Show formula
        self.play(FadeIn(explicit_formula))

        # 6. Add approximation with increasing zeros
        zero_lbl = make_zero_lbl(1)
        self.play(
            Create(app_1, rate_func=linear),
            FadeIn(zero_lbl),
            run_time=2.0
        )

        zero_lbl2 = make_zero_lbl(5)
        self.play(
            Transform(app_1, app_5, rate_func=smooth),
            Transform(zero_lbl, zero_lbl2),
            run_time=2.0
        )
        self.wait(0.8)

        zero_lbl3 = make_zero_lbl(20)
        self.play(
            Transform(app_1, app_20, rate_func=smooth),
            Transform(zero_lbl, zero_lbl3),
            run_time=2.5
        )
        self.wait(0.8)

        zero_lbl4 = make_zero_lbl(50)
        self.play(
            Transform(app_1, app_50, rate_func=smooth),
            Transform(zero_lbl, zero_lbl4),
            run_time=2.5
        )
        self.wait(0.5)

        # 7. Legend
        self.play(FadeIn(legend), run_time=0.8)

        # 8. Observation text
        obs = Text(
            "More zeros → better approximation to M(x)",
            font_size=20, color=MINT
        ).to_edge(DOWN, buff=0.3)
        self.play(Write(obs), run_time=1.2)
        self.wait(2.5)

        # Final fade
        self.play(*[FadeOut(m) for m in self.mobjects], run_time=1.5)
        self.wait(0.5)


def pdf_v2(weights, x_values, N=2**20, t_max=3000.0):
    dt = t_max / N
    t = np.arange(N, dtype=np.float64) * dt
    phi = np.ones(N)
    for w in weights:
        phi *= j0(w * t)
    phi[0] = 1.0
    rfft_phi = np.fft.rfft(phi)
    pdf_grid = (dt / np.pi) * np.real(rfft_phi)
    n_out = N // 2 + 1
    dx = 2.0 * np.pi / (N * dt)
    x_grid = np.arange(n_out) * dx
    x_full = np.concatenate([-x_grid[::-1], x_grid[1:]])
    pdf_full = np.concatenate([pdf_grid[::-1], pdf_grid[1:]])
    # NO clipping
    interp = interp1d(x_full, pdf_full, kind='linear', bounds_error=False, fill_value=0.0)
    return interp(x_values)

class ArcSinCombo(Scene):
    def construct(self):
        # Gibbs-like ringing outside support. The clippling to 0 is losing probability mass.
        # Better: increase t_max significantly to reduce ringing, and don't clip.
        # For arcsin, the CF J_0(t) decays as 1/sqrt(t) so ringing is expected.
        # The right fix: use more points to reduce Gibbs oscillations by smoothing.
        # OR: just not clip, and accept small negatives from Gibbs.
        # Let's try without clipping:


        # x = np.linspace(-1.5, 1.5, 50000)
        # p = pdf_v2([1.0], x)
        # print('Integral (no clip):', np.trapezoid(p, x))
        # x2 = np.linspace(-0.999, 0.999, 20000)
        # p2 = pdf_v2([1.0], x2)
        # ana = 1/(np.pi * np.sqrt(1 - x2**2))
        # print('Max error |x|<0.999:', np.max(np.abs(p2 - ana)))
        # print('Integral inner:', np.trapezoid(p2, x2))

        nterms = 5


        npts = 2000
        xvals = np.linspace(-1, 1, npts)
        yvals = pdf_v2([0.8], xvals, t_max=5000., N=2**20)

        ax = Axes(x_range=[xvals[0], xvals[-1] * 1.05], x_length=12, y_length=7, y_range=[0, 2],
                  axis_config={'color': WHITE, 'stroke_width': 4,
                               'include_ticks': False, 'include_tip': True})

        plt = ax.plot_line_graph(xvals, yvals, add_vertex_dots=False, line_color=BLUE, stroke_width=6)

        self.add(ax, plt)

if __name__ == "__main__":
    with tempconfig({"quality": "low_quality", "preview": True, 'fps': 15}):
        # MertensScene().render()
        ArcSinCombo().construct()
